import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import { SanityLive } from "@/sanity/live";
import { ClerkProvider } from "@clerk/nextjs";
import HeaderCategorySelector from "@/components/HeaderCategorySelector";
import { Toaster } from "@/components/ui/sonner";
import getTotalOrderForHeader from "@/components/Order/getTotalOrderForHeader";
import GetTotalOrderForHeader from "@/components/Order/getTotalOrderForHeader";

// const inter = Inter({
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`antialiased`}
        >
          <Header 
            categorySelector={<HeaderCategorySelector/>}
            totalOrder={<GetTotalOrderForHeader/>}
          />
          {children}
          <SanityLive />
          <Toaster/>
        </body>
      </html>
    </ClerkProvider>
  );
}
